@TM:1201489851
@N: BN191 :"":0:0:0:-1|Writing property annotation file E:\EMB002\project\hardware\CPLD\pld\pld.tap.
@N: BN225 :"":0:0:0:-1|Writing default property annotation file E:\EMB002\project\hardware\CPLD\pld\pld.map.
@N: FA174 :"":0:0:0:-1|The following device usage report estimates place and route data. Please look at the place and route report for final resource usage..
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1201489849
@N: CG364 :"e:\emb002\project\hardware\cpld\pld.v":1:7:1:9|Synthesizing module pld
@TM:1206005652
@W: CL159 :"e:\emb002\project\hardware\cpld\pld.v":4:6:4:13|M
@W: CL159 :"e:\emb002\project\hardware\cpld\pld.v":6:6:6:13|M
@W: CL159 :"e:\emb002\project\hardware\cpld\pld.v":7:6:7:12|M
@TM:1206008519
@W: CL159 :"e:\emb002\project\hardware\cpld\pld.v":10:6:10:11|M
@TM:1206007869
@W: CG133 :"e:\emb002\project\hardware\cpld\pld.v":28:10:28:14|M
@W: CG133 :"e:\emb002\project\hardware\cpld\pld.v":29:10:29:18|M
@TM:1206007871
@W:  :"e:\emb002\project\hardware\cpld\pld.v":35:15:35:24|M
@TM:1206007972
@N:  :"e:\emb002\project\hardware\cpld\pld.v":68:0:68:5|M
@TM:1206007971
@W: CL169 :"e:\emb002\project\hardware\cpld\pld.v":68:0:68:5|M
@TM:1206007972
@N:  :"e:\emb002\project\hardware\cpld\pld.v":101:0:101:5|M
@TM:1206007971
@W: CL170 :"e:\emb002\project\hardware\cpld\pld.v":101:0:101:5|M
@TM:1206007972
@N:  :"e:\emb002\project\hardware\cpld\pld.v":185:0:185:5|M
@TM:1206008519
@W: CL169 :"e:\emb002\project\hardware\cpld\pld.v":199:0:199:5|M
@W: CL169 :"e:\emb002\project\hardware\cpld\pld.v":211:0:211:5|M
