/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT framework.cdb */

#define CHIP_DM642 1

/*  Include Header Files  */
#include <std.h>
#include <buf.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <que.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern far BUF_Obj BUF_imgPool;
extern far BUF_Obj BUF_copyPool;
extern far BUF_Obj BUF_imgCap;
extern far BUF_Obj BUF_capFrame;
extern far HST_Obj RTA_fromHost;
extern far HST_Obj RTA_toHost;
extern far SWI_Obj KNL_swi;
extern far TSK_Obj TSK_idle;
extern far TSK_Obj TSK_image;
extern far TSK_Obj TSK_algorithm;
extern far LOG_Obj LOG_system;
extern far LOG_Obj trace;
extern far QUE_Obj img_queue;
extern far QUE_Obj result_queue;
extern far QUE_Obj match_queue;
extern far STS_Obj IDL_busyObj;
extern far STS_Obj stsCycleTime;
extern far STS_Obj stsDispTime;
extern far STS_Obj stsExeTimeChJpegDec;
extern far STS_Obj stsExeTimeChJpegEnc;
extern far STS_Obj stsCapTime;
extern far void CSL_cfgInit();

#ifdef __cplusplus
}
#endif /* extern "C" */
