
cmp start_batch

project start_batch

project start_batch pld
cmp add_assignment "" "" "" ROOT "|pld"
cmp add_assignment "" "" "" FAMILY "CYCLONE II"
cmp add_assignment "pld" "" "" DEVICE "EP2C5T144C8"
project add_assignment "" "pld" "" "" "EDA_DESIGN_ENTRY_SYNTHESIS_TOOL" "SYNPLIFY"
project add_assignment "" "eda_design_synthesis" "" "" "EDA_USE_LMF" "synplcty.lmf"
project add_assignment "" "nWE_setting" "" "" "DUTY_CYCLE" "50"
project add_assignment "pld" "" "" "nWE" "GLOBAL_SIGNAL" "ON"
project add_assignment "pld" "" "" "nWE" "USE_CLOCK_SETTINGS" "nWE_setting"
project add_assignment "" "nWE_setting" "" "" "FMAX_REQUIREMENT" "1.0MHZ"
project add_assignment "" "|Button_1:Button_FW|Button_FW_clk_1k_setting" "" "" "DUTY_CYCLE" "50"
project add_assignment "pld" "" "" "|Button_1:Button_FW|Button_FW_clk_1k" "USE_CLOCK_SETTINGS" "|Button_1:Button_FW|Button_FW_clk_1k_setting"
project add_assignment "" "|Button_1:Button_FW|Button_FW_clk_1k_setting" "" "" "FMAX_REQUIREMENT" "1.0MHZ"
project add_assignment "" "|Button:Button_FQ|Button_FQ_clk_1k_setting" "" "" "DUTY_CYCLE" "50"
project add_assignment "pld" "" "" "|Button:Button_FQ|Button_FQ_clk_1k" "GLOBAL_SIGNAL" "ON"
project add_assignment "pld" "" "" "|Button:Button_FQ|Button_FQ_clk_1k" "USE_CLOCK_SETTINGS" "|Button:Button_FQ|Button_FQ_clk_1k_setting"
project add_assignment "" "|Button:Button_FQ|Button_FQ_clk_1k_setting" "" "" "FMAX_REQUIREMENT" "1.0MHZ"
project add_assignment "" "|Wigend_In_2:wigend_in3|wigend_in3_wil_clk_setting" "" "" "DUTY_CYCLE" "50"
project add_assignment "pld" "" "" "|Wigend_In_2:wigend_in3|wil_clk_i" "GLOBAL_SIGNAL" "ON"
project add_assignment "pld" "" "" "|Wigend_In_2:wigend_in3|wil_clk_i" "USE_CLOCK_SETTINGS" "|Wigend_In_2:wigend_in3|wigend_in3_wil_clk_setting"
project add_assignment "" "|Wigend_In_2:wigend_in3|wigend_in3_wil_clk_setting" "" "" "FMAX_REQUIREMENT" "1.0MHZ"
project add_assignment "" "|Wigend_In_1:wigend_in2|wigend_in2_wil_clk_setting" "" "" "DUTY_CYCLE" "50"
project add_assignment "pld" "" "" "|Wigend_In_1:wigend_in2|wil_clk_i" "GLOBAL_SIGNAL" "ON"
project add_assignment "pld" "" "" "|Wigend_In_1:wigend_in2|wil_clk_i" "USE_CLOCK_SETTINGS" "|Wigend_In_1:wigend_in2|wigend_in2_wil_clk_setting"
project add_assignment "" "|Wigend_In_1:wigend_in2|wigend_in2_wil_clk_setting" "" "" "FMAX_REQUIREMENT" "1.0MHZ"
project add_assignment "" "|Wigend_In:wigend_in1|wigend_in1_wil_clk_setting" "" "" "DUTY_CYCLE" "50"
project add_assignment "pld" "" "" "|Wigend_In:wigend_in1|wil_clk_i" "GLOBAL_SIGNAL" "ON"
project add_assignment "pld" "" "" "|Wigend_In:wigend_in1|wil_clk_i" "USE_CLOCK_SETTINGS" "|Wigend_In:wigend_in1|wigend_in1_wil_clk_setting"
project add_assignment "" "|Wigend_In:wigend_in1|wigend_in1_wil_clk_setting" "" "" "FMAX_REQUIREMENT" "1.0MHZ"
project add_assignment "" "clk_setting" "" "" "DUTY_CYCLE" "50"
project add_assignment "pld" "" "" "clk" "GLOBAL_SIGNAL" "ON"
project add_assignment "pld" "" "" "clk" "USE_CLOCK_SETTINGS" "clk_setting"
project add_assignment "" "clk_setting" "" "" "FMAX_REQUIREMENT" "1.0MHZ"
project add_assignment "" "" "" "" "TAO_FILE" "myresults.tao"
project add_assignment "" "" "" "" "SOURCES_PER_DESTINATION_INCLUDE_COUNT" "1000"
project add_assignment "" "" "" "" "ROUTER_REGISTER_DUPLICATION" "ON"
project add_assignment "pld" "" "|Wigend_In_2:wigend_in3|wigend_in3.wil_clk"  "data\[0\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_1:wigend_in2|wigend_in2.wil_clk"  "data\[0\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In:wigend_in1|wigend_in1.wil_clk"  "data\[0\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "data\[0\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_2:wigend_in3|wigend_in3.wil_clk"  "data\[1\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_1:wigend_in2|wigend_in2.wil_clk"  "data\[1\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In:wigend_in1|wigend_in1.wil_clk"  "data\[1\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "data\[1\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_2:wigend_in3|wigend_in3.wil_clk"  "data\[2\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_1:wigend_in2|wigend_in2.wil_clk"  "data\[2\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In:wigend_in1|wigend_in1.wil_clk"  "data\[2\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "data\[2\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "data\[3\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_2:wigend_in3|wigend_in3.wil_clk"  "data\[3\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_1:wigend_in2|wigend_in2.wil_clk"  "data\[3\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In:wigend_in1|wigend_in1.wil_clk"  "data\[3\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "data\[3\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_2:wigend_in3|wigend_in3.wil_clk"  "data\[4\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_1:wigend_in2|wigend_in2.wil_clk"  "data\[4\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In:wigend_in1|wigend_in1.wil_clk"  "data\[4\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "data\[4\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_2:wigend_in3|wigend_in3.wil_clk"  "data\[5\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_1:wigend_in2|wigend_in2.wil_clk"  "data\[5\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In:wigend_in1|wigend_in1.wil_clk"  "data\[5\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "data\[5\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_2:wigend_in3|wigend_in3.wil_clk"  "data\[6\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_1:wigend_in2|wigend_in2.wil_clk"  "data\[6\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In:wigend_in1|wigend_in1.wil_clk"  "data\[6\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "data\[6\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_2:wigend_in3|wigend_in3.wil_clk"  "data\[7\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_1:wigend_in2|wigend_in2.wil_clk"  "data\[7\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In:wigend_in1|wigend_in1.wil_clk"  "data\[7\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "data\[7\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "WIL_OUT\[0\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "WIL_OUT\[1\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_2:wigend_in3|wigend_in3.wil_clk"  "IRQ"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In_1:wigend_in2|wigend_in2.wil_clk"  "IRQ"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Wigend_In:wigend_in1|wigend_in1.wil_clk"  "IRQ"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "IRQ"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "SW_LCD"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "SW_CCD1"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "SW_CCD2"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "SW_CCD3"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "AD_CLK"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "AD_CS"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "GIO1"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "GIO2"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "GIO3"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "GIO4"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "KEYout\[0\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "KEYout\[1\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "KEYout\[2\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "KEYout\[3\]"  "TCO_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "nOE"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "nOE"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "nCE"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "nCE"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "nWE"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "nWE"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "addr\[0\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "addr\[0\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "addr\[1\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "addr\[1\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "addr\[2\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "addr\[2\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "addr\[3\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "addr\[3\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "addr\[4\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "addr\[4\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "addr\[5\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "addr\[5\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "addr\[6\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "addr\[6\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "addr\[7\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "addr\[7\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "data\[0\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "data\[1\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "data\[2\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "data\[3\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "data\[4\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "data\[5\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "data\[6\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "nWE"  "data\[7\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "WIL_IN\[0\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "WIL_IN\[1\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "WIL_IN_A\[0\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "WIL_IN_A\[1\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "WIL_IN_B\[0\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "WIL_IN_B\[1\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Button:Button_FQ|Button_FQ.clk_1k"  "FQ"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "|Button_1:Button_FW|Button_FW.clk_1k"  "FW"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "AD_DO"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "KEYin\[0\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "KEYin\[1\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "KEYin\[2\]"  "TSU_REQUIREMENT"  "1000.000ns"
project add_assignment "pld" "" "clk"  "KEYin\[3\]"  "TSU_REQUIREMENT"  "1000.000ns"

# False path constraints 

# Multicycle constraints 

# Path delay constraints 

project end_batch pld

project end_batch

cmp end_batch
